### ISSUE TITLE
pwr-only usb, and microsd access?

### ISSUE THREAD

**Issue by jdlcdl** [orangesurf/orangesurf-seedsigner-case#3]
It's a beautiful case, but some considerations that come to mind:

* It looks like the full-featured usb port is available, instead of the pwr-only usb port exclusively.

* The most recent seedsigner release, and those into the future, allow pulling the microsd as soon as seedsigner boots, so that there is no possibility of anything being stored permanently while loading seeds, but it would need to be accessible while seedsigner is assembled.

* It seems like the names on the STL files are swapped, clicking the body gets user to the cover, and vice versa.

Beautiful case!  Nice work!  All the best!

**Comment by orangesurf** [comment]
Thanks @jdlcdl 

- Switched to pwr-only usb port exclusively in v5 (&v6)
- Intention with this design was that people would be able to glue the screws into position making disassembly for an evil maid attack obvious. I could explore a version which enables easy removal of the microsd in the future.
- The names are correct in the latest release (v6)

Thank you for your help
